### PR TITLE
feat: update to Capacitor v6

### PR DESCRIPTION
**Pull request by eric-horodyski**
This PR updates `@capacitor-community/photoviewer` to Capacitor 6.

> While I work at Ionic, I want to clarify that this contribution was made during my personal time. This is a personal contribution to the Capacitor community, and is not related to my work responsibilities. As such, I won't be able to maintain this plugin or assist with inquiries about contacting Ionic employees.

A big thanks to @jepiqueau for all the contributions to the Capacitor Community,.

## Changes

- Plugin migrated from Capacitor 5 to Capacitor 6 by running `npx @capacitor/plugin-migration-v5-to-v6@latest`, per [plugin update docs](https://capacitorjs.com/docs/updating/plugins/6-0).
-  Fix compilation issue when targeting Android SDK 34 (#56). Credit to @andrerds for the solution. 
- Major version bump.

## Testing

**Testers wanted**. Minimal testing has been performed after updating using the example app on a PIxel 6 (Android 14) and iPhone 15 (iOS 17.0) simulator, with no issues reported.  

I _do not_ use this plugin and do not have the bandwidth or frame-of-reference to properly battle-test. It would be appreciated if users of this plugin could run a smoke test against their apps (after [updating to Capacitor 6](https://capacitorjs.com/docs/updating/6-0)) and comment on this PR with their results. 

## Plugin maintenance

If you are interested in performing the role of maintainer for this plugin, please comment in the `#capacitor-community` channel of the [Ionic Discord Server](https://discord.gg/UPYYRhtyzp).

### CODE REVIEW

**Comment by jepiqueau** [comment]
@eric-horodyski Thanks for this. This morning, @robingenz accepts to ensure the maintenance of the plugin. So discuss with him for the PR merge and the npm publish

**Comment by z0lo13** [comment]
@robingenz any eta on this ?

**Comment by robingenz** [comment]
@eric-horodyski Seems like i miss some permissions in this repository. For example, i cannot create new milestones. Could you please check this?

**Comment by eric-horodyski** [comment]
Hey @robingenz, I don't have permission myself to make these adjustments (I work on the customer engineering side of the house). My colleagues on the [Ionic Discord](https://discord.gg/UPYYRhtyzp) should be able to assist (you'll want the `#capacitor-community` channel).

**Comment by robingenz** [comment]
@eric-horodyski Please resolve the last merge conflict.

**Review by robingenz — APPROVED** [review]

**Pull request merged**
