### PR TITLE
chore: Add editor changes

### PR DESCRIPTION
**Pull request by jcesarmobile**
[This PR](https://github.com/capacitor-community/photoviewer/commit/c90169529e806362faf16db887d3c4efe308b782) introduced some vscode automatic formatting.

This PR just saves the files so the editor re arranges imports and add missing ending lines.

### CODE REVIEW

**Review by robingenz — APPROVED** [review]
Thanks!

**Comment by robingenz** [comment]
It seems that the formatting is not correct now (see https://github.com/capacitor-community/photoviewer/actions/runs/10631116351/job/29471356650?pr=67). Possibly only whitespaces. Please try to run `npm run fmt`.

**Comment by jcesarmobile** [comment]
fmt fixes the lint problem, but saving the file reintroduces the lint problem, so looks like it's not working as expected?

**Comment by jcesarmobile** [comment]
If there is no new line it adds it, but if there is one it still adds another one, only happens on the index.ts file.

**Pull request merged**
